### PR TITLE
fix: use latest API (`loader-utils`)

### LINKED ISSUE #59: [3.0.0-beta] query.substr is not a function
Tried installing 3.0.0-beta to see if it would get rid of the parseQuery warning, and instead I'm getting this error for every file:
```
ERROR in ./src/helpers/promise.ts
Module build failed: TypeError: query.substr is not a function
    at Object.parseQuery (/Users/dpogue/Coding/project/node_modules/loader-utils/lib/parseQuery.js:12:11)
    at Object.exports.default (/Users/dpogue/Coding/project/node_modules/istanbul-instrumenter-loader/dist/index.js:17:43)
 @ ./src/helpers/promise.spec.ts 3:0-49
 @ ./src .spec.ts$
 @ ./webpack.tests.js
```

### PR DESCRIPTION
**Pull request by mattlewis92**
Fixes #59

This repo could probably do with some tests that would have caught this, unfortunately I don't have time right now to contribute them as well. I tested it locally in my project and it worked ok with these changes.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -10,8 +10,8 @@ export default function (source, sourceMap) {
     srcMap = inlineSourceMap.sourcemap;
   }
 
-  const userOptions = loaderUtils.parseQuery(this.query);
-  const instrumenter = istanbulLibInstrument.createInstrumenter(
+  const userOptions = loaderUtils.getOptions(this);
```
Comment (michael-ciniawsky) [inline src/index.js]:
```diff
- const userOptions = loaderUtils.getOptions(this);
+ const userOptions = loaderUtils.getOptions(this) || {};
```

`loaderUtils.getOptions()` returns `null`, if there aren't any options

Comment (mattlewis92) [inline src/index.js]: This is safe as passing null as an arg to Object.assign just has it skip it without an error `Object.assign({foo: 'bar'}, null) == {foo: 'bar'}`

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
